# Generated by Django 4.2.1 on 2023-05-04 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roupa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('C', 'Calça'), ('C', 'Calça'), ('C', 'Calça'), ('C', 'Calça'), ('C', 'Calça'), ('C', 'Calça'), ('C', 'Calça')], default='C', max_length=1)),
            ],
        ),
    ]
