# Generated by Django 4.2.1 on 2023-05-04 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roupa', '0002_roupa_cor_roupa_lugar_roupa_reparo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roupa',
            name='observacao',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
