# Generated by Django 4.2.1 on 2023-05-04 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roupa', '0003_roupa_observacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sacola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
                ('status', models.CharField(choices=[('pronto', 'Pronto'), ('proent', 'Pronto e Entregue'), ('afazer', 'A Fazer')], default='afazer', max_length=8)),
                ('situacao', models.CharField(choices=[('pago', 'Pago'), ('naopago', 'Não Pago'), ('ptpago', 'Pagou uma parte')], default='naopago', max_length=8)),
                ('observecao_sacola', models.TextField(blank=True, max_length=255, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoSacola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('data_entrega', models.DateField()),
                ('preco', models.FloatField()),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roupa.roupa')),
                ('sacola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sacola.sacola')),
            ],
            options={
                'verbose_name': 'Item da sacola',
                'verbose_name_plural': 'Itens da sacola',
            },
        ),
    ]
