# Generated by Django 4.2.1 on 2023-05-04 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sacola', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtosacola',
            old_name='produto',
            new_name='roupa',
        ),
    ]
