# Generated by Django 4.2.1 on 2023-05-05 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacola', '0002_rename_produto_produtosacola_roupa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtosacola',
            name='data_entrega',
        ),
        migrations.AddField(
            model_name='sacola',
            name='data_entrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
